version: '3'

services:

  redis:
    image: redis:4
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    env_file:
      - bootstrap-kafka.env
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '8082:8082'
      - '8083:8083'
